repos:
   - repo: local
     hooks:
        - id: dune-build-fmt
          name: dune build @fmt
          entry: dune build @fmt --auto-promote
          pass_filenames: false
          language: system
          types: [text]
          stages: [pre-push]
        - id: dune-build-opam
          name: dune build
          entry: dune build @install
          pass_filenames: false
          language: system
          types: [text]
          stages: [pre-push]
