name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy doc
    runs-on: ubuntu-latest
    container: ghcr.io/c-cube/c-cube-commmon/ci-doc-5.3:latest

    steps:
      - uses: actions/checkout@v6

      - name: Deps
        run: opam install containers containers-data

      - name: Build
        run: opam exec -- odig odoc --cache-dir=_doc/ containers containers-data

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_doc/html/
          destination_dir: .
          enable_jekyll: false
