name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - ocaml-version: "4.08"
            container: ghcr.io/c-cube/c-cube-commmon/ci-4.08:latest
          - ocaml-version: "4.14"
            container: ghcr.io/c-cube/c-cube-commmon/ci-4.14:latest
          - ocaml-version: "5.4"
            container: ghcr.io/c-cube/c-cube-commmon/ci-5.4:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6
      - run: opam install -t containers containers-data --deps-only
      - run: opam exec -- dune build '@install'
      - run: opam exec -- dune runtest --force --profile=release
